$$
Matrices = \left\{
    \begin{array}\\
        3x+4y+5z=2\\ 
        -1x -2y -3z=4 \\
        -5x + 2y +3z=6
    \end{array}
\right. $$

$$
\begin{bmatrix}3&4&5\\-1&-2&-3\\-5&2&3\end{bmatrix} \cdot \begin{bmatrix}x\\ y\\ z\end{bmatrix} = \begin{bmatrix}2\\4\\6\end{bmatrix}
$$

In [12]:
import numpy as np

In [18]:
A = np.array([
              [3,4,5],
              [-1,-2,-3],
              [-5,2,3]
])

B = np.array([
              [2],
              [4],
              [6]
])

In [22]:
print("A = \n", X)
print("\nB = \n", Y)

A = 
 [[ 3  4  5]
 [-1 -2 -3]
 [-5  2  3]]

B = 
 [[2]
 [4]
 [6]]


In [23]:
X_inv = np.linalg.inv(X)
Xinv_Y = X_inv @ Y

print(Xinv_Y)

[[ -1.66666667]
 [ 16.33333333]
 [-11.66666667]]


In [24]:
x_y = np.linalg.solve(X, Y)

print(x_y)

[[ -1.66666667]
 [ 16.33333333]
 [-11.66666667]]


In [25]:
ans1 = X @ Xinv_Y
np.allclose(ans1, Y)

True